# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0,5,10,15,20 * * *'   # +8 等于北京时间（8,13,18,23,4）点(5左右分钟延时)

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout #同步仓库
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Do auto #开始签到
      run: | 
        python ./auto_a.py

